### ISSUE TITLE
trace: atomic.AddUint64(nextSpanID) causes segmentation violation due to misalignment on 32-bit architectures

### ISSUE THREAD

**Issue by lukatendai** [census-instrumentation/opencensus-go#865]
Hi, 
I am keep getting segmentation violation after updating to the latest version... It looks like the problem is here, but it could be caused by other libraries that call this one.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804926c]

goroutine 3441 [running]:
sync/atomic.AddUint64(0x1986f66c, 0x8c3989df, 0xd1f43496, 0x6f8f1912, 0x52bbc414)
    /home/luke/bin/go/src/sync/atomic/asm_386.s:112 +0xc
bitbucket.org/xxx/xxx/vendor/go.opencensus.io/trace.(*defaultIDGenerator).NewSpanID(0x1986f650, 0x0, 0x0)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/go.opencensus.io/trace/trace.go:483 +0x4c
bitbucket.org/xxx/xxx/vendor/go.opencensus.io/trace.startSpanInternal(0x19d33cb0, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/go.opencensus.io/trace/trace.go:196 +0x95
bitbucket.org/xxx/xxx/vendor/go.opencensus.io/trace.StartSpan(0x90d75c0, 0x1a0074e0, 0x19d33cb0, 0x22, 0x19a7d8dc, 0x2, 0x2, 0xfffef7ff, 0xef, 0x0)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/go.opencensus.io/trace/trace.go:162 +0x14c
bitbucket.org/xxx/xxx/vendor/go.opencensus.io/plugin/ochttp.(*traceTransport).RoundTrip(0x1a0073a0, 0x19896680, 0x1a0b9580, 0x1, 0x1)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/go.opencensus.io/plugin/ochttp/trace.go:58 +0xfc
bitbucket.org/xxx/xxx/vendor/go.opencensus.io/plugin/ochttp.statsTransport.RoundTrip(0x90d11f0, 0x1a0073a0, 0x19896680, 0x19caaac8, 0x19caaac8, 0x8abcd80)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/go.opencensus.io/plugin/ochttp/client_stats.go:54 +0x2ed
bitbucket.org/xxx/xxx/vendor/go.opencensus.io/plugin/ochttp.(*Transport).RoundTrip(0x19f2ca40, 0x19896600, 0x19896600, 0x0, 0x8057868)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/go.opencensus.io/plugin/ochttp/client.go:89 +0x17e
bitbucket.org/xxx/xxx/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0x19f2cbc0, 0x19f5c200, 0x0, 0x0, 0x0)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/golang.org/x/oauth2/transport.go:56 +0xd4
net/http.send(0x19f5c200, 0x90d1290, 0x19f2cbc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19f5c200, 0x19caae08, ...)
    /home/luke/bin/go/src/net/http/client.go:252 +0x151
net/http.(*Client).send(0x19f2cbe0, 0x19f5c200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0xb76fbf5b, 0xb76fbf02, ...)
    /home/luke/bin/go/src/net/http/client.go:176 +0xaa
net/http.(*Client).Do(0x19f2cbe0, 0x19f5c200, 0x19828160, 0x19f5c200, 0x0)
    /home/luke/bin/go/src/net/http/client.go:615 +0x23c
bitbucket.org/xxx/xxx/vendor/golang.org/x/net/context/ctxhttp.Do(0x90d7580, 0x19828160, 0x19f2cbe0, 0x19f5c180, 0x0, 0x0, 0x19f1f864)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:30 +0x59
bitbucket.org/xxx/xxx/vendor/google.golang.org/api/gensupport.SendRequest(0x90d7580, 0x19828160, 0x19f2cbe0, 0x19f5c180, 0x19a7ddbc, 0x19f2cdc0, 0x19f5c180)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/google.golang.org/api/gensupport/send.go:53 +0x142
bitbucket.org/xxx/xxx/vendor/google.golang.org/api/storage/v1.(*ObjectsInsertCall).doRequest(0x19d31560, 0x8b43385, 0x4, 0x0, 0x0, 0x0)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/google.golang.org/api/storage/v1/storage-gen.go:8948 +0x490
bitbucket.org/xxx/xxx/vendor/google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0x19d31560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/google.golang.org/api/storage/v1/storage-gen.go:8960 +0x76
bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage.(*Writer).open.func1.2(0x0, 0x80577ec)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage/writer.go:156 +0x3f
bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage.runWithRetry.func1(0x19a8f240, 0x19b2a588, 0x8057868)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage/invoke.go:27 +0x1c
bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/internal.retry(0x90d7580, 0x19828160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/internal/retry.go:39 +0x37
bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/internal.Retry(0x90d7580, 0x19828160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/internal/retry.go:32 +0x48
bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage.runWithRetry(0x90d7580, 0x19828160, 0x19ada7c8, 0xffffffff, 0x0)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage/invoke.go:26 +0x52
bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage.(*Writer).open.func1(0x1a08a5a0, 0x1a0961e0, 0x19caac08, 0x19caac18, 0x1, 0x1)
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage/writer.go:154 +0x58b
created by bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage.(*Writer).open
    /home/luke/golang/src/bitbucket.org/xxx/xxx/vendor/cloud.google.com/go/storage/writer.go:108 +0x3e6`
```

**Comment by ramonza** [comment]
Hi @lukatendai, thanks for the bug report.

Could you give the output of running "go env" with the toolchain you use to compile this program?

**Comment by odeke-em** [comment]
Thanks @lukatendai for the report and @ramonza for handling it.

I wanted to chime to perhaps suggest that this might be a symptom of a memory misalignment bug in Go that manifests because of the way our fields are organized in the struct `defaultIDGenerator`. We've already encountered the ARM variant of this bug in https://github.com/census-instrumentation/opencensus-go/issues/587, but not yet on 32 bit machines so your report is the first but this is the first bug report given that that code just got added freshly 2 weeks ago in https://github.com/census-instrumentation/opencensus-go/commit/5f0e92a92d90ebeaf2662ca76981a5a21243fb91 aka PR https://github.com/census-instrumentation/opencensus-go/pull/851 

My Maths could be terribly wrong as I haven't slept in a while, but here is my analysis and what
I can see is that for
https://github.com/census-instrumentation/opencensus-go/blob/457d67e3f41e6e1861cf86f5bd9390e46272ecb0/trace/trace.go#L471-L477

### On a 32 bit system intel i386 as referenced in the issue's stacktrace
* The sync.Mutex as per https://github.com/golang/go/blob/c882f4b6b13d4d38d354bec4614d4402031ec1b1/src/sync/mutex.go#L25-L28
```go
type Mutex struct {
        state int32
        sema  uint32
}
```
has a size of 4 + 4 bytes = 8 bytes

* traceIDRand *rand.Rand has a size of 4 bytes as it is a pointer on a 32 bit machine
* traceIDAdd  [2]uint64 has a size of 8 * 2 bytes = 16 bytes, as it is an array of 2 elements each of 8 bytes
* nextSpanID has a size of 8 bytes (but accessed as low and high)
* spanIDInc has a size of 8 bytes (but accessed as low and high)

Total: 8 + 4 + 16 + 8 + 8 = 44 bytes and (eventually 4 extra bytes of padding to give aligned size of 48 for the struct)
 
Notice that the code
https://github.com/census-instrumentation/opencensus-go/blob/457d67e3f41e6e1861cf86f5bd9390e46272ecb0/trace/trace.go#L483
nextSpanID isn't aligned
as it is accessible as the 28th byte: from the start of the struct, until the 36th byte: [28-32, 32-36]

which I believe we can fix by making nextSpanID the first field, followed by spanIDInc... and have the mutex last. Any other suggestions are highly welcome.

**Comment by odeke-em** [comment]
Actually I can reproduce this by using `GOARCH=386` while running tests
```shell
$ GOARCH=386 go test
```

**Comment by lukatendai** [comment]
sure, thx for working on this...

**Comment by odeke-em** [comment]
@lukatendai I've mailed out https://github.com/census-instrumentation/opencensus-go/issues/865, PTAL -- the fix is basically making the pointer field the last one, since the size of a pointer on 32-bit machines is 4 bytes hence misaligns 8 byte fields to be on non-divisible by 8 boundaries
